// var source = {
//   "Motor Insurance": [
//     "Motor Insurance",
//     "التأمين على السيارات",
//   ],
//   "From Chassis Number": ["From Chassis Number", "من رقم الشاسيه"],
//   "From Vehicle Info": ["From Vehicle Info", "من معلومات السيارة"],
//   "From Plate Number": ["From Plate Number", "من رقم اللوحة"],
//   "Profile": ["Profile", "حساب تعريفي"],
//   "Contact": ["Contact", "اتصال"],
//   "Help": ["Help", "يساعد"],
//   "Home": ["Home", "مسكن"],
//   "Enter Chassis No": ["Enter Chassis No", ""],
//   "Chassis No*": ["Chassis No*", "رقم الشاسيه"],
//   "Proceed": ["Proceed", "تقدم"],
//   "Chassis no can be found on the back side of your Istimara (Vehicle registration card)": [
//     "Chassis no can be found on the back side of your Istimara (Vehicle registration card)",
//     "لا يمكن العثور على الهيكل على الجانب الخلفي من الاستمارة الخاصة بك (بطاقة تسجيل السيارة)"
//   ],
//   "Enter Vehicle Info": ["Enter Vehicle Info", ""],
//   "Model Year*": ["Model Year*", ""],
//   "Make*": ["Make*", ""],
//   "Model*": ["Model*", ""],
//   "Seating Capacity*": ["Seating Capacity*", ""],
//   "TrimType*": ["TrimType*", ""],
//   "Enter Vehicle Details": ["Enter Vehicle Details", ""],
//   "Vehicle Type*": ["Vehicle Type*", ""],
//   "Vehicle Usage*": ["Vehicle Usage*", ""],
//   "No of cylinder*": ["No of cylinder*", ""],
//   "Car Registration Year*": ["Car Registration Year*", ""],
//   "Registration Location*": ["Registration Location*", ""],
//   "GCC Specification*": ["GCC Specification*", ""],
//   "Yes": ["Yes", ""],
//   "No": ["No", ""],
//   "Geographical Location": ["Geographical Location", ""],
//   "Enter Personal Info": ["Enter Personal Info", ""],
//   "First Name*": ["First Name*", ""],
//   "Last Name": ["Last Name", ""],
//   "Date Of Birth*": ["Date Of Birth*", ""],
//   "Nationality*": ["Nationality*", ""],
//   "Driving Experience*": ["Driving Experience*", ""],
//   "Vehicle Value*": ["Vehicle Value*", ""],
//   "Civil Id*": ["Civil Id*", ""],
//   "Gender*": ["Gender*", ""],
//   "Enter Policy Info": ["Enter Policy Info", ""],
//   "Policy Start Date*": ["Policy Start Date*", ""],
//   "Policy End Date": ["Policy End Date", ""],
//   "Email Id*": ["Email Id*", ""],
//   "Mobile Number*": ["Mobile Number*", ""],
//   "Promo code*": ["Promo code", ""],
//   "Select Plan": ["Select Plan", ""],
//   "Quotation No:": ["Quotation No:", ""],
//   "Policy From Date": ["Policy From Date", ""],
//   "Your Premium": ["Your Premium", ""],
//   "Deductibles,": ["Deductibles,", ""],
//   "Info": ["Info", ""],
//   "Add More Cover": ["Add More Cove", ""],
//   "Additional Vehicle Info": ["Additional Vehicle Info", ""],
//   "Plate Character*": ["Plate Character*", ""],
//   "Plate No*": ["Plate No*", ""],
//   "Enter Plate Information": ["Enter Plate Information*", ""],
//   "Plate Type*": ["PlateType*", ""],
//   "Engine Number*": ["Engine Number*", ""],
//   "Additional Personal Info": ["Additional Personal Info", ""],
//   "Insured Type*": ["Insured Type*", ""],
//   "Address*": ["Address*", ""],
//   "P.O.BOX*": ["P.O.BOX*", ""],
//   "City*": ["City*", ""],
//   "Additional Driver Details": ["Additional Driver Details", ""],
//   "Driver": ["Driver", ""],
//   "Driver Name*": ["Driver Name*", ""],
//   "Driver age*": ["Driver age*", ""],
//   "Driver License No": ["Driver License No", ""],
//   "Driver License Age": ["Driver License Age", ""],
//   "Relationship": ["Relationship", ""],
//   "Tell Us About Home Contents": ["Tell Us About Home Contents", ""],
//   "Building Value": ["Building Value", ""],
//   "Total Approximate Value Of Your Home Contents": ["Total Approximate Value Of Your Home Contents", ""],
//   "Enter Promo Code*": ["Enter Promo Code", ""],
//   "Household Comprehensive Insurance": ["Household Comprehensive Insurance", ""],
//   "OMR": ["OMR", ""],
//   "Select policy start date": ["Select policy start date", ""],
//   "Building Address": ["Building Address", ""],
//   "Zone/Area": ["Zone/Area", ""],
//   "Street/Block": ["Street/Block", ""],
//   "Age Of Buliding": ["Age Of Buliding", " "],
//   "Type Of Buliding": ["Type Of Buliding", ""],
//   "Policy Holder Information": ["Policy Holder Information", ""],
//   "Insured Name*": ["Insured Name*", ""],
//   "Under Writing Question": ["Under Writing Question", ""],
//   "Tick If Yes": ["Tick If Yes", ""],
//   "Upload The Documents": ["Upload The Documents", ""],
//   "Civil ID Front Side*": ["Civil ID Front Side*", ""],
//   "Image Source": ["Image Source", ""],
//   "Upload ": ["Upload", ""],
//   "No File Selected ": ["No File Selected ", ""],
//   "Civil ID Back Side*": ["Civil ID BackSide*", ""],
//   "Building Mulkiya*": ["Building Mulkiya*", ""],
//   "Building Photo*": ["Building Value*", ""],
//   "Insurance And Type Of Trip": ["Insurance And Type Of Trip*", ""],
//   "Type Of Trip": ["Type Of Trip", ""],
//   "Travelling Abroad": ["Travelling Abroad", ""],
//   "Visiting Oman": ["Visiting Oman", ""],
//   "Single": ["Single", ""],
//   "Multiple": ["Multiple", ""],
//   "Out Bound": ["Out Bound", ""],
//   "In Bound": ["In Bound", ""],
//   "A One-Off Trip": ["A One-Off Trip", ""],
//   "Several Trips": ["Several Trips", ""],
//   "Choose Your Travel Dates": ["Choose Your Travel Dates", ""],
//   "Number Of Travel Days": ["Number Of Travel Days", ""],
//   "Choose Start Date": ["Choose Start Date", ""],
//   "Choose End Date": ["Choose End Date", ""],
//   "Total Persons": ["Total Persons", ""],
//   "Total Adult(Age)": ["Total Adult(Age)", ""],
//   "Total Child(Age)": ["Total Child(Age)", ""],
//   "Select Your Plan": ["Select Your Plan", ""],
//   "Depature Date": ["Depature Date", ""],
//   "Return Date": ["Return Date", ""],
//   "Travel Type": ["Travel Type", ""],
//   "Travel Days": ["Travel Days", ""],
//   "Travelers": ["Travelers", ""],
//   "Single trip": ["Single trip", ""],
//   "Adults": ["Adults", ""],
//   "Child": ["Child", ""],
//   "Regional*": ["Regional*", ""],
//   "Premium": ["Premium", ""],
//   "Fixed Payment": ["Fixed Payment", ""],
//   "Included Covers": ["Included Covers", ""],
//   "Terrorism Extension": ["Terrorism Extension", ""],
//   "Emergency Medical Covers": ["Emergency Medical Covers", ""],
//   "Travel Inconvenience Covers": ["Travel Inconvenience Covers", ""],
//   "Disounts": ["Disounts", ""],
//   "Online Special Disount": ["Online Special Disount", ""],
//   "Total Premium": ["Total Premium", ""],
//   "Travel Excess(USD)": ["Travel Excess(USD)", ""],
//   "Additional Covers": ["Additional Covers", ""],
//   "Covers All People": ["Covers All People", ""],
//   "Net Payable": ["Net Payable", ""],
//   "Winter Sports Extension": ["Winter Sports Extension", ""],
//   "Tell Us About You": ["Tell Us About You", ""],
//   "Hello,Guest": ["Hello,Guest", ""],
//   "Passport No*": ["Passport No*", ""],
//   "Get Quote In @ Mins!": ["Get Quote In @ Mins!", ""],
//   "Comprehensive Insurance": ["Comprehensive Insurance", ""],
//   "Third Party Liability Insurance": ["Third Party Liability Insurance", ""],
//   "Third Party Liability Plus Insurance": ["Third Party Liability  Plus Insurance", ""],
//   "Home Insurance": ["Home Insurance", ""],
//   "Travel Insurance": ["Travel Insurance", ""],
//   "Expiry Date": ["Expiry Date", ""],
//   "Quote No": ["Quote No", ""],
//   "Quote Date": ["Quote Date", ""],
//   "Policy No": ["Policy No", ""],
//   "Insurance Type": ["Insurance Type", ""],
//   "PROCEED TO BUY": ["PROCEED TO BUY", ""],
//   "VIEW": ["VIEW", ""],
//   "Active Policies": ["Active Policies", ""],
//   "Complete Your Pending Quotations": ["Complete Your Pending Quotations", ""],
//   "Looking For More?": ["Looking For More?", ""],
//   "Intimate Claim": ["Intimate Claim", ""],
//   "My Claim": ["My Claim", ""],
//   "Discounts And Promotions": ["Discounts And Promotions", ""],
//   "Contact Us": ["Contact Us", ""],
//   "FAQ's": ["FAQ's", ""],
//   "Login": ["Login", ""],
//   "Register here": ["Register here", ""],
//   "Don't have an account": ["Don't have an account", ""],
//   "Continue as a Guest": ["Continue as a Guest", ""],
//   "Civil ID or Email*": ["Civil ID or Email*", ""],
//   "Intimate Claim or Renew Policy": ["Intimate Claim or Renew Policy", ""],
//   "Would you like to": ["Would you like to", ""],
//   "Hotline": ["Hotline", ""],
//   "info@oqic-insured.com": ["info@oqic-insured.com", ""],
//   "Whatsapp Chat": ["Whatsapp Chat", ""],
// };

var language_source = {};
